language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
#install:
#  - pip install .
#  - pip install -r requirements.txt
# command to run tests
script: python -m pytest -v tests/
env:
  - PYTHONPATH=''
